services:
  - type: web
    name: api-biblioteca
    env: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: centerbeam.proxy.rlwy.net
      - key: DB_PORT
        value: 44492
      - key: DB_DATABASE
        value: railway
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        value: ycTuUJtiFJIHFOVcRbcQqwUIBgpahlpR
